export enum MissionActionTypes {
	FETCH_MISSIONS = 'FETCH_MISSIONS',
	FETCH_MISSIONS_SUCCESS = 'FETCH_MISSIONS_SUCCESS',
	FETCH_MISSIONS_ERROR = 'FETCH_MISSIONS_ERROR'



}




export enum UserActionTypes {
	FETCH_USER = 'FETCH_USER',
	FETCH_USER_ERROR = 'FETCH_USER_ERROR',
	FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',


}